name: Output information
#run manually from the Actions tab
on: workflow_dispatch
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output a message
        run: echo "${{toJSON(github)}}"